[package]
name = "pie"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version="1.0", features = ["derive"]}
serde_yaml = "0.9"
postgres = "0.19.5"
regex = "1.9.3"
clap = "4.4.0"
colored = "2.0.4"
serde_json = "1.0.108"
chrono = "0.4.31"
